# Purchase & costs
price: 250000.0
notary_pct: 7.5 # %
agency_pct: 3 # %
renovation_costs: 10000.0
extra_fees: 2000.0

# Loan
loan_rate: 3 # %
loan_years: 20
down_payment: 50000.0

# Recurring costs
property_tax_annual: 1200.0
other_taxes_annual: 0.0
insurance_rate_on_initial_per_year: 0.25  # 0.25%
copro_charges_annual: 1200.0
copro_growth_rate: 2 # %
maintenance_rate_of_value: 1 # %

# Growth & timeline
benchmark_return_rate: 5 # %
price_growth_rate: 0 # %
inflation_rate: 2 # %
invest_duration: 5

# Discounting
discount_rate: 4 # % (taux d'actualisation commun)


# Rental specific
occupancy_rate: 0.92
rent_monthly: 1100.0
rent_growth_rate: 2 # %
management_fee_rate: 6 # %
rental_tax_rate: 30 # %

# Exit costs/taxes
selling_fees_rate: 5 # %
capital_gains_eff_rate: 0 # % for RP by default
include_early_repayment_penalty: true
benchmark_rent_monthly: 800.0

